repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements  # This is only for Python

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Sort imports
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: "/usr/bin/bash -c 'cd src/backend && .env/bin/python'"
      args: ["-m", "pytest"]
      language: script
      pass_filenames: false
      # alternatively you could `types: [python]` so it only runs when python files change
      # though tests might be invalidated if you were to say change a data file
      always_run: true
