services:
  backend:
    build:
      context: "./src/backend"
      dockerfile: "../../infrastructure/Dockerfile"
    expose:
      - "8000/tcp"
    volumes:
      - "./src/backend:/app"
      - "./infrastructure/bootstrap.sh:/app/bootstrap.sh"
    env_file:
      - "backend.env"
    entrypoint: "./bootstrap.sh"
    depends_on:
      - db
    command: ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    image: "nginx"
    ports:
      - "7500:80/tcp"
    volumes:
      - "./dist:/usr/share/nginx/html"
      - "./infrastructure/nginx.conf:/etc/nginx/nginx.conf"
      - "./infrastructure/default.conf.template:/etc/nginx/conf.d/default.conf.template"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - backend
    env_file:
      - "frontend.env"
  db:
    image: "postgres:17.0"
    env_file:
      - "db.env"
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
